name: Publish Python Package to PyPI

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    name: Build and Publish to PyPI
    runs-on: ubuntu-latest

    environment: PyPI Publish

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v5

      - name: Build package
        run: uv build

      - name: Publish package
        run: uv publish --token ${{ secrets.PYPI_PUBLISH_KEY }}
